POST http://localhost:3001/admin-panel/post/schedule
Content-Type: application/json

{
    "title": "test2",
    "description": "test",
    "priority": "low",
    "students": [144, 142, 141],
    "groups": [132]
}