PUT http://localhost:3001/admin-panel/post/schedule/8/recievers
Content-Type: application/json

# {
#     "title": "testing update",
#     "description": "description",
#     "priority": "medium",
#     "scheduled_at": "2025-07-09T00:00:00.000Z",
#     "image": null
# }

{
    "students": [7],
    "groups": []
}