name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  install-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd backend
          npm ci

      - name: Build the Project
        run: |
          cd backend
          npm run build

      - name: Zip the Files
        run: |
          cd backend
          (cd dist && zip -r ../backend.zip .) && zip -ur backend.zip node_modules package.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: backend/backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: install-and-build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-package
          path: backend

      - name: Move ZIP file to root
        run: mv backend/backend.zip backend.zip

      - name: Deploy to AWS Lambda
        uses: docker://amazon/aws-cli
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        with:
          entrypoint: /usr/local/bin/aws
          args: >-
            lambda update-function-code
            --function-name ParentsAdminAPI
            --zip-file fileb://backend.zip
